name: android_play_install_referrer
description: >
  A Flutter plugin for the Android Play Install Referrer API.
  You can use it to securely retrieve referral content from Google Play.
version: 0.0.4
homepage: https://github.com/lschmierer/android_play_install_referrer

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ">=1.12.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  plugin:
    platforms:
      android:
        package: de.lschmierer.android_play_install_referrer
        pluginClass: AndroidPlayInstallReferrerPlugin
